/**:
  behavior_server_node:
    ros__parameters:
      costmap_topic: local_costmap/costmap_raw
      footprint_topic: local_costmap/published_footprint
      cycle_frequency: 10.0
      behavior_plugins: ["spin", "backup", "drive_on_heading", "assisted_teleop", "wait"]
      spin:
        plugin: "nav2_behaviors/Spin"
      backup:
        plugin: "nav2_behaviors/BackUp"
      drive_on_heading:
        plugin: "nav2_behaviors/DriveOnHeading"
      wait:
        plugin: "nav2_behaviors/Wait"
      assisted_teleop:
        plugin: "nav2_behaviors/AssistedTeleop"
      global_frame: odom
      robot_base_frame: base_link
      transform_tolerance: 0.1
      use_sim_time: true
      simulate_ahead_time: 2.0
      max_rotational_vel: 1.0
      min_rotational_vel: 0.4
      rotational_acc_lim: 3.2